### ISSUE TITLE
studentify use instructions should be clarified

### ISSUE THREAD

**Issue by renghen** [lunatech-labs/lunatech-scala-2-to-scala3-course#63]
on a **fresh** clone of the repo lunatech-scala-2-to-scala3-course.

I have tried the following studentify -dot /home/renghen/workspace/dotty/lunatech-scala-2-to-scala3-course /home/renghen/workspace/lunatech-course 

But got 

YOU HAVE CHANGES IN YOUR GIT WORKSPACE. COMMIT CHANGES AND RE-RUN STUDENTIFY
  Executed command: cmt-checkIfWorkspaceClean.sh /home/renghen/workspace/dotty/lunatech-scala-2-to-scala3-course
  Working directory: .

**Comment by renghen** [comment]
Hi again,

I was able to fix it. In the file core/src/main/scala/com/lightbend/coursegentools/Helpers.scala.

we should add bin/ on line 589 and on line 273.

so on line 273 it becomes "bin/cmt-cpCleanViaGit.sh"
and on line 589 it becomes s"""bin/cmt-checkIfWorkspaceClean.sh ${mainRepo.getPath}"""

**Comment by robinraju** [comment]
@renghen thanks for reaching out to us. 
The [Course Management Tools](https://github.com/eloots/course-management-tools) is in active development. This is a known issue and will be fixed in the upcoming release of the tool. 

You can also download the `studentified` artifact from [Releases](https://github.com/lunatech-labs/lunatech-scala-2-to-scala3-course/releases) named `lunatech-scala-2-to-scala3-course-student.zip`

**Comment by eloots** [comment]
@renghen
To add to what @robinraju said: we will generate binaries for the CMT commands (`mainadm`, `studentify`, `linearize` and `delinearize`) as part of our CI/CD chain.
These will come with the `cmt-cpCleanViaGit.sh` and `cmt-checkIfWorkspaceClean.sh`supporting script.
When installing them, you'll need to adapt your PATH to accommodate them.
This is the fix you can apply when running the commands as you did: add the `bin` folder in the course management repo to your PATH.

**Comment by eloots** [comment]
@renghen We just released [version 1.0.0 of the Course Management Tools](https://github.com/eloots/course-management-tools/releases/tag/1.0.0) (CMT). You have binaries of the different CMT commands and installation instructions.
